[package]
name = "mandelbrot-rs"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
image = "0.25.8"
num = "0.4.3"
rayon = "1.11.0"
